### ISSUE TITLE
Tests failing on awscli build 2.9.4

### ISSUE THREAD

**Issue by davdunc** [davdunc/awscli-2-rpm#51]
### RPM build failure on 2.9.4 

+ cd aws-cli-2.9.4
+ PATH=/var/home/davdunc/src/awscli-2-rpm/rpmbuild/BUILDROOT/awscli-2-2.9.4-1.fc37.x86_64/usr/bin:/var/home/davdunc/.local/bin:/var/home/davdunc/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ PYTHONPATH=/var/home/davdunc/src/awscli-2-rpm/rpmbuild/BUILDROOT/awscli-2-2.9.4-1.fc37.x86_64/usr/lib64/python3.11/site-packages:/var/home/davdunc/src/awscli-2-rpm/rpmbuild/BUILDROOT/awscli-2-2.9.4-1.fc37.x86_64/usr/lib/python3.11/site-packages
+ PYTHONDONTWRITEBYTECODE=1
+ /usr/bin/python3 scripts/ci/run-tests
Running pytest --numprocesses=auto --dist=loadfile --maxprocesses=4 unit/ functional/...
ImportError while loading conftest '/var/home/davdunc/src/awscli-2-rpm/rpmbuild/BUILD/aws-cli-2.9.4/tests/conftest.py'.
__init__.py:27: in <module>
    from awscli.clidriver import create_clidriver, AWSCLIEntryPoint
../../../BUILDROOT/awscli-2-2.9.4-1.fc37.x86_64/usr/lib/python3.11/site-packages/awscli/clidriver.py:21: in <module>
    import botocore.session
../../../BUILDROOT/awscli-2-2.9.4-1.fc37.x86_64/usr/lib/python3.11/site-packages/awscli/botocore/session.py:27: in <module>
    import botocore.client
../../../BUILDROOT/awscli-2-2.9.4-1.fc37.x86_64/usr/lib/python3.11/site-packages/awscli/botocore/client.py:16: in <module>
    from botocore import UNSIGNED, waiter, xform_name
../../../BUILDROOT/awscli-2-2.9.4-1.fc37.x86_64/usr/lib/python3.11/site-packages/awscli/botocore/waiter.py:17: in <module>
    from botocore.docs.docstring import WaiterDocstring
../../../BUILDROOT/awscli-2-2.9.4-1.fc37.x86_64/usr/lib/python3.11/site-packages/awscli/botocore/docs/__init__.py:15: in <module>
    from botocore.docs.service import ServiceDocumenter
../../../BUILDROOT/awscli-2-2.9.4-1.fc37.x86_64/usr/lib/python3.11/site-packages/awscli/botocore/docs/service.py:14: in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
../../../BUILDROOT/awscli-2-2.9.4-1.fc37.x86_64/usr/lib/python3.11/site-packages/awscli/botocore/docs/client.py:16: in <module>
    from botocore.docs.example import ResponseExampleDocumenter
../../../BUILDROOT/awscli-2-2.9.4-1.fc37.x86_64/usr/lib/python3.11/site-packages/awscli/botocore/docs/example.py:13: in <module>
    from botocore.docs.shape import ShapeDocumenter
../../../BUILDROOT/awscli-2-2.9.4-1.fc37.x86_64/usr/lib/python3.11/site-packages/awscli/botocore/docs/shape.py:19: in <module>
    from botocore.utils import is_json_value_header
../../../BUILDROOT/awscli-2-2.9.4-1.fc37.x86_64/usr/lib/python3.11/site-packages/awscli/botocore/utils.py:15: in <module>
    import cgi
/usr/lib64/python3.11/cgi.py:57: in <module>
    warnings._deprecated(__name__, remove=(3,13))
/usr/lib64/python3.11/warnings.py:514: in _deprecated
    warn(msg, DeprecationWarning, stacklevel=3)
E   DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
Traceback (most recent call last):
  File "/var/home/davdunc/src/awscli-2-rpm/rpmbuild/BUILD/aws-cli-2.9.4/scripts/ci/run-tests", line 91, in <module>
    run(cmd, allow_repo_root_on_path=raw_args.allow_repo_root_on_path)
  File "/var/home/davdunc/src/awscli-2-rpm/rpmbuild/BUILD/aws-cli-2.9.4/scripts/ci/run-tests", line 31, in run
    return check_call(command, shell=True, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'pytest --numprocesses=auto --dist=loadfile --maxprocesses=4 unit/ functional/' returned non-zero exit status 4.
error: Bad exit status from /var/tmp/rpm-tmp.k8gKVC (%check)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.k8gKVC (%check)
error: File not found by glob: rpmbuild/RPMS/x86_64/awscli-2*.rpm
make: *** [Makefile:34: awscli-2] Error 1

**Comment by Conan-Kudo** [comment]
It looks like here the failure is caused by the deprecation warning being emitted. Can we get rid of or replace the `import cgi` call in `awscli.botocore.utils`?

**Comment by davdunc** [comment]
```
$ grep -ir "import cgi" rpmbuild/BUILD/aws-cli-2.9.4/* 
rpmbuild/BUILD/aws-cli-2.9.4/awscli/botocore/utils.py:import cgi
rpmbuild/BUILD/aws-cli-2.9.4/build/unpacked_wheel/awscli/botocore/utils.py:import cgi

```

**Comment by davdunc** [comment]
Found the following related commit https://github.com/boto/botocore/pull/2794/commits/e891fa05caa8c6ec9d016b0207554e01e14164f5
